### ISSUE TITLE
神翻译！Translater is so nb.

### ISSUE THREAD

**Issue by SteamFinder** [picasso250/spring12#1]
是不是应该改成Spring12Boom而不是twelve_biubiu.....................

**Comment by cccxm** [comment]
> 是不是应该改成Spring12Boom而不是twelve_biubiu.....................

999(6翻了)

**Comment by halu886** [comment]
觉得spring_festival_12_boom会更好一点（滑稽）

**Comment by picasso250** [comment]
这段程序原作者是李一一，他就是这么写的。他是这么一个不拘小节的人，我也没办法。

**Comment by umud66** [comment]
少一个` biu` 很不爽

**Comment by kyle-wang** [comment]
我仔细看了一下，李一一当时的界面是用的Java
